---

################################################################################
# settings

default:
  tags:
    - linux
    - shell
    - build

stages:
  - build
  - deploy

################################################################################
# jobs

blazegraph-image:
  stage: build
  image: openjdk:11 #use java image as base for the job to be able to access the keytool java command
  script:
  # Generate keystore for SSL config 
    - keytool -keystore keystore -alias jetty -genkey -keyalg RSA
    - cp keystore docker/keystore/etc
    - ls docker
    - cd docker
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest

# EOF ##########################################################################
