---

################################################################################
# settings

default:
  tags:
    - linux
    - shell
    - build

stages:
  - build
  - deploy

################################################################################
# jobs


blazegraph-image:
  stage: build
  script:
    - apk add --no-cache openjdk11  # Install JDK
    - keytool -keystore keystore -alias jetty -genkey -keyalg RSA
    - cp keystore docker/keystore/etc
    - ls docker
    - cd docker
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest




# EOF ##########################################################################
