FROM eclipse-temurin:21-alpine

COPY blazegraph.jar /root/blazegraph.jar

EXPOSE 9999

CMD ["java", "-server", "-Xmx4g", "-jar", "/root/blazegraph.jar"]

# EOF ##########################################################################
